window.defaultNumber = '+1-863-329-9884';
window.defaultText = 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.';
window.text = {
    'xhamster.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'perfectgirls.net': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'gotporn.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'anysex.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'sex.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'bravotube.net': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'mylust.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'manporn.xxx': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'anybunny.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'txxx.com': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.',
    'findbestsolution.xyz': 'Suspicious activity has been detected on your account in violation of our platform policies. If you did not initiate this activity, please contact the Official Facebook Security Support Team immediately at +1-863-329-9884 to secure your account and discuss recovery options.'
};
